FROM maven:3.8.5-openjdk-17 as builder

COPY ./executable/eim-0.1.0.jar /executable/eim-0.1.0.jar

RUN MODULES="$(jdeps --list-deps --ignore-missing-deps /executable/eim-0.1.0.jar | tail -n +2 | tr -d ' ' | tr '\n' ',')" && \
    echo "MODULES=${MODULES}" && \
    MODULES="${MODULES}" \
    jlink \
    --module-path ${JAVA_HOME}/jmods \
    --add-modules ${MODULES} \
    --verbose \
    --strip-debug \
    --compress 2\
    --no-header-files \
    --no-man-pages \
    --output /opt/jre-minimal

FROM bitnami/minideb:bullseye

COPY --from=builder /opt/jre-minimal /opt/jre-minimal

ENV JAVA_HOME=/opt/jre-minimal
ENV PATH="$PATH:$JAVA_HOME/bin"

COPY --from=builder  /executable/eim-0.1.0.jar /eim-0.1.0.jar

ENTRYPOINT ["/opt/jre-minimal/bin/java","-jar","/eim-0.1.0.jar"]